[package]

name = "postgres_macros"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.0.0"

build = "build.rs"

[lib]

name = "postgres_macros"
path = "src/lib.rs"
plugin = true
test = false
